### PR TITLE
Add SpriteFetcher.js to js_utilities

### PR DESCRIPTION
**Pull request by misscs**
Move this shared utility to central place for maintainability and shareability across
all projects

### CODE REVIEW

**Comment by victorwhy** [comment]
This doesn't need to be included in any calls / tasks here?  is this just so that it's included within this repo so that it's available natively?

**Comment by misscs** [comment]
@victorwhy exactly. it will be called in the libraries. eventually i see us moving shared JS in `n-core` and may end up calling it. I will issue two PRs on `storefront-static` and `nightshade` with this update. Once I update our jspm useage in rails (as part of the js cleanup) we'll be able to use nightshade-core js in rails app.

**Comment by misscs** [comment]
@victorwhy / @robwierzbowski good to go with this one? would be good to get this into the next release so i can update the other repos and open PRs.

**Comment by robwierzbowski** [comment]
DTM. Are you going to make a PR to Casper Rails too?

**Comment by robwierzbowski** [comment]
Wait! Can we hypenate the folder? I haven't seen us use underscored folders anywhere else in our apps.

**Comment by robwierzbowski** [comment]
Huh, never mind, you do here. Commenting on a phone, takes a little while to research.

**Comment by misscs** [comment]
We underscore for compatibility/sameness/convention with rails. Bough we
could make a case to switch later. I'm also ++ for hyphens

**Comment by josephco** [comment]
DTM from me

**Comment by robwierzbowski** [comment]
Consistency is all I care about! DTM!

**Pull request merged**
